language: python
python:
  - "2.7"
env:
  - NUMPY_VERSION=""
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy${NUMPY_VERSION} scipy matplotlib openpyxl=1.8.2 pandas nose flake8 pep8
  - source activate env_name
  - pip install sphinx sphinx-bootstrap-theme coverage coveralls
  - pip install -e '.[all]'
script:
  - python tests/all_tests.py --ili_scripts_dir scripts
  - nosetests ili --with-coverage --cover-package=ili --cover-inclusive tests
  # - make -C doc html
after_success:
  - coveralls
